/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Inference */

#ifndef _Included_Inference
#define _Included_Inference
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Inference
 * Method:    dsdgemm
 * Signature: ([I[D[D)V
 */
JNIEXPORT void JNICALL Java_Inference_dsdgemm
  (JNIEnv *, jobject, jintArray, jdoubleArray, jdoubleArray);

/*
 * Class:     Inference
 * Method:    sddgemm
 * Signature: ([I[D[D)V
 */
JNIEXPORT void JNICALL Java_Inference_sddgemm
  (JNIEnv *, jobject, jintArray, jdoubleArray, jdoubleArray);

/*
 * Class:     Inference
 * Method:    ssdgemm
 * Signature: ([I[D)LCSCMatrix;
 */
JNIEXPORT jobject JNICALL Java_Inference_ssdgemm
  (JNIEnv *, jobject, jintArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
